# Generated by Django 4.0.1 on 2022-01-31 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3)),
                ('grupo', models.CharField(choices=[('T', 'Técnico-Administrativo'), ('D', 'Docente')], max_length=1)),
                ('nome', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('C', 'Fundamental'), ('D', 'Médio'), ('E', 'Superior'), (' ', 'Docente')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=60)),
                ('umae', models.CharField(max_length=60)),
            ],
        ),
    ]
