# Generated by Django 4.0.1 on 2022-02-01 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='codigo',
            field=models.CharField(max_length=3, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nivel',
            field=models.CharField(choices=[('C', 'Fundamental'), ('D', 'Médio'), ('E', 'Superior'), ('X', 'Docente')], max_length=1, verbose_name='nível'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='codigo',
            field=models.CharField(max_length=60, verbose_name='código'),
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siape', models.CharField(max_length=7, unique=True, verbose_name='SIAPE')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=70)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('cor', models.CharField(choices=[('0', ''), ('1', 'Branca'), ('3', 'Amarela'), ('4', 'Parda'), ('5', 'Indígena'), ('6', 'Preta'), ('9', 'Não informada')], max_length=1, verbose_name='cor/Raça')),
                ('email', models.EmailField(max_length=125, unique=True, verbose_name='e-mail')),
                ('local', models.CharField(choices=[('J', 'Juazeiro do Norte'), ('B', 'Barbalha'), ('C', 'Crato'), ('S', 'Brejo Santo'), ('M', 'Multiuso')], max_length=1)),
                ('dt_nasc', models.DateField(verbose_name='nascimento')),
                ('ch', models.CharField(default='40', max_length=2, verbose_name='carga horária(h)')),
                ('dt_exerc_sp', models.DateField(verbose_name='início do serviço púlbico')),
                ('dt_desligamento', models.DateField(blank=True, null=True, verbose_name='data de desligamento')),
                ('dt_inclusao', models.DateField(auto_now_add=True, verbose_name='inclusão')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Lotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_entrada', models.DateField(verbose_name='data de entrada')),
                ('dt_saida', models.DateField(verbose_name='data de saída')),
                ('dt_inclusao', models.DateField(auto_now_add=True, verbose_name='inclusão')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.servidor')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unidade')),
            ],
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=128, verbose_name='descrição')),
                ('codigo', models.CharField(choices=[('CD1', 'Cargo de Direção 1'), ('CD2', 'Cargo de Direção 2'), ('CD3', 'Cargo de Direção 3'), ('CD4', 'Cargo de Direção 4'), ('FG1', 'Função Gratificada 1'), ('FG2', 'Função Gratificada 2'), ('FG3', 'Função Gratificada 3'), ('FG4', 'Função Gratificada 4'), ('FUC1', 'Coordenação de Curso')], max_length=4444, verbose_name='código')),
                ('dt_entrada', models.DateField(verbose_name='data de entrada')),
                ('dt_saida', models.DateField(verbose_name='data de saída')),
                ('dt_inclusao', models.DateField(auto_now_add=True, verbose_name='inclusão')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.servidor')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unidade')),
            ],
        ),
    ]
