# Generated by Django 4.0.1 on 2022-02-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_servidor_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='email',
            field=models.EmailField(max_length=125, verbose_name='e-mail'),
        ),
    ]
