# Generated by Django 4.0.1 on 2022-02-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_servidor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotacao',
            name='dt_saida',
            field=models.DateField(blank=True, null=True, verbose_name='data de saída'),
        ),
    ]
