# Generated by Django 4.0.1 on 2022-02-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_lotacao_dt_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcao',
            name='codigo',
            field=models.CharField(choices=[('CD1', 'Cargo de Direção 1'), ('CD2', 'Cargo de Direção 2'), ('CD3', 'Cargo de Direção 3'), ('CD4', 'Cargo de Direção 4'), ('FG1', 'Função Gratificada 1'), ('FG2', 'Função Gratificada 2'), ('FG3', 'Função Gratificada 3'), ('FG4', 'Função Gratificada 4'), ('FUC1', 'Coordenação de Curso')], max_length=4, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='funcao',
            name='dt_saida',
            field=models.DateField(blank=True, null=True, verbose_name='data de saída'),
        ),
    ]
