# Generated by Django 4.0.1 on 2022-02-24 19:12

import core.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_funcao_codigo_alter_funcao_dt_saida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcao',
            options={'verbose_name': 'Função', 'verbose_name_plural': 'Funções'},
        ),
        migrations.AlterModelOptions(
            name='lotacao',
            options={'ordering': ['-dt_entrada'], 'verbose_name': 'Lotação', 'verbose_name_plural': 'Lotações'},
        ),
        migrations.AlterModelOptions(
            name='servidor',
            options={'verbose_name_plural': 'Servidores'},
        ),
        migrations.AlterField(
            model_name='funcao',
            name='codigo',
            field=models.CharField(choices=[('CD1', 'CD 000.1'), ('CD2', 'CD 000.2'), ('CD3', 'CD 000.3'), ('CD4', 'CD 000.4'), ('FG1', 'FG 000.1'), ('FG2', 'FG 000.2'), ('FG3', 'FG 000.3'), ('FG4', 'FG 000.4'), ('FUC1', 'FUC 000.1')], max_length=4, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='lotacao',
            name='dt_entrada',
            field=models.DateField(default=datetime.date(2022, 2, 24), verbose_name='data de entrada'),
        ),
        migrations.AlterField(
            model_name='lotacao',
            name='unidade',
            field=models.ForeignKey(default=core.models.get_default_lotacao, on_delete=django.db.models.deletion.PROTECT, to='core.unidade'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='cor',
            field=models.CharField(choices=[('0', '-'), ('1', 'Branca'), ('3', 'Amarela'), ('4', 'Parda'), ('5', 'Indígena'), ('6', 'Preta'), ('9', 'Não informada')], max_length=1, verbose_name='cor/Raça'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='umae',
            field=models.CharField(max_length=60, verbose_name='unidade mãe'),
        ),
    ]
