# Generated by Django 4.0.1 on 2022-06-08 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_funcao_options_alter_lotacao_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotacao',
            name='dt_entrada',
            field=models.DateField(default=datetime.date(2022, 6, 8), verbose_name='data de entrada'),
        ),
    ]
