# Generated by Django 4.0.1 on 2022-06-10 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_lotacao_dt_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotacao',
            name='dt_entrada',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='data de entrada'),
        ),
    ]
