# Generated by Django 4.0.1 on 2022-06-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grafico',
            options={'ordering': ['titulo']},
        ),
    ]
